Models/UserRoleGroups.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace Medcs.Models
{
    public partial class UserRoleGroups
    {
        public int Id { get; set; }
        [DisplayName("User")]
        public int UserId { get; set; }
        [DisplayName("Role Group")]
        public int RoleGroupId { get; set; }

        public RoleGroups RoleGroup { get; set; }
        public Users User { get; set; }
    }
}

Controllers/UserRoleGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Medcs.Models;

namespace Medcs.Controllers
{
    public class UserRoleGroupsController : Controller
    {
        private readonly medicalcenterContext _context;

        public UserRoleGroupsController(medicalcenterContext context)
        {
            _context = context;
        }

        // GET: UserRoleGroups
        public async Task<IActionResult> Index()
        {
            var medicalcenterContext = _context.UserRoleGroups.Include(u => u.RoleGroup).Include(u => u.User);
            return View(await medicalcenterContext.ToListAsync());
        }

        // GET: UserRoleGroups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userRoleGroups = await _context.UserRoleGroups
                .Include(u => u.RoleGroup)
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userRoleGroups == null)
            {
                return NotFound();
            }

            return View(userRoleGroups);
        }

        // GET: UserRoleGroups/Create
        public IActionResult Create()
        {
            ViewData["RoleGroupId"] = new SelectList(_context.RoleGroups, "Id", "Name");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Name");
            return View();
        }

        // POST: UserRoleGroups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,RoleGroupId")] UserRoleGroups userRoleGroups)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userRoleGroups);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleGroupId"] = new SelectList(_context.RoleGroups, "Id", "Name", userRoleGroups.RoleGroupId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Name", userRoleGroups.UserId);
            return View(userRoleGroups);
        }

        // GET: UserRoleGroups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userRoleGroups = await _context.UserRoleGroups.FindAsync(id);
            if (userRoleGroups == null)
            {
                return NotFound();
            }
            ViewData["RoleGroupId"] = new SelectList(_context.RoleGroups, "Id", "Name", userRoleGroups.RoleGroupId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Name", userRoleGroups.UserId);
            return View(userRoleGroups);
        }

        // POST: UserRoleGroups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,RoleGroupId")] UserRoleGroups userRoleGroups)
        {
            if (id != userRoleGroups.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userRoleGroups);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserRoleGroupsExists(userRoleGroups.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleGroupId"] = new SelectList(_context.RoleGroups, "Id", "Name", userRoleGroups.RoleGroupId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Name", userRoleGroups.UserId);
            return View(userRoleGroups);
        }

        // GET: UserRoleGroups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userRoleGroups = await _context.UserRoleGroups
                .Include(u => u.RoleGroup)
                .Include(u => u.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userRoleGroups == null)
            {
                return NotFound();
            }

            return View(userRoleGroups);
        }

        // POST: UserRoleGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userRoleGroups = await _context.UserRoleGroups.FindAsync(id);
            _context.UserRoleGroups.Remove(userRoleGroups);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserRoleGroupsExists(int id)
        {
            return _context.UserRoleGroups.Any(e => e.Id == id);
        }
    }
}

Views/UserRoleGroups/Create.cshtml
@model Medcs.Models.UserRoleGroups

@{
    ViewData["Title"] = "Create";
}

<h2><b>Assign UserRoleGroups</b></h2>

@*<h4></h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="RoleGroupId" class="control-label"></label>
                <select asp-for="RoleGroupId" class ="form-control" asp-items="ViewBag.RoleGroupId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/UserRoleGroups/Delete.cshtml
@model Medcs.Models.UserRoleGroups

@{
    ViewData["Title"] = "Delete";
}

<h2><b>Delete</b></h2>

<h3>Are you sure you want to delete this UserRoleGroups?</h3>
<hr />
<div>
    @*<h4></h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RoleGroup)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RoleGroup.Name)
        </dd>

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/UserRoleGroups/Details.cshtml
@model Medcs.Models.UserRoleGroups

@{
    ViewData["Title"] = "Details";
}

<h2>Details of the UserRoleGroups</h2>

<div>
    @*<h4></h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoleGroup)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RoleGroup.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/UserRoleGroups/Edit.cshtml
@model Medcs.Models.UserRoleGroups

@{
    ViewData["Title"] = "Edit";
}

<h2><b>Edit UserRoleGroups</b></h2>

@*<h4></h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoleGroupId" class="control-label"></label>
                <select asp-for="RoleGroupId" class="form-control" asp-items="ViewBag.RoleGroupId"></select>
                <span asp-validation-for="RoleGroupId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/UserRoleGroups/Index.cshtml
@model IEnumerable<Medcs.Models.UserRoleGroups>

@{
    ViewData["Title"] = "Index";
}

<h2><b>User Role Groups</b></h2>

<p>
    @Html.ActionLink("+Add New User Role Groups", "Create", "UserRoleGroups", null, new { @class = "btn btn-danger" })

</p>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@

<table id="userrolegroups" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RoleGroup)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.User.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoleGroup.Name)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>