Models/Clinics.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Medcs.Models
{
    public partial class Clinics
    {
        public Clinics()
        {
            Appointments = new HashSet<Appointments>();
            Inventories = new HashSet<Inventories>();
            Sessions = new HashSet<Sessions>();
            Settlements = new HashSet<Settlements>();
            SubscriptionInvoices = new HashSet<SubscriptionInvoices>();
            Users = new HashSet<Users>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        [Required(ErrorMessage = "You must provide a Register Number")]
        [DisplayName("Registration Number")]
        public string RegNo { get; set; }
        [Required(ErrorMessage = "You must provide a Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "You must provide a phone number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string Phone { get; set; }
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public DateTime SubscribedAt { get; set; }
        public string BillingCycle { get; set; }
        public byte IsActive { get; set; }

        public ICollection<Appointments> Appointments { get; set; }
        public ICollection<Inventories> Inventories { get; set; }
        public ICollection<Sessions> Sessions { get; set; }
        public ICollection<Settlements> Settlements { get; set; }
        public ICollection<SubscriptionInvoices> SubscriptionInvoices { get; set; }
        public ICollection<Users> Users { get; set; }
    }
}

Controllers/ClinicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Medcs.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace Medcs.Controllers
{

    //[Authorize(Roles = "admin")]

    public class ClinicsController : Controller
    {
        private readonly medicalcenterContext _context;

        public ClinicsController(medicalcenterContext context)
        {
            //if(!string.IsNullOrEmpty(HttpContext.Session.GetString("user_id")))
            //{
            //    LocalRedirect("/login");
            //}
            _context = context;
        }

        // GET: Clinics
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clinics.ToListAsync());
        }

        // GET: Clinics/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clinics = await _context.Clinics
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clinics == null)
            {
                return NotFound();
            }

            return View(clinics);
        }

        // GET: Clinics/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clinics/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,RegNo,Address,Phone,Email,SubscribedAt,BillingCycle,IsActive")] Clinics clinics)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clinics);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(clinics);
        }

        // GET: Clinics/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clinics = await _context.Clinics.FindAsync(id);
            if (clinics == null)
            {
                return NotFound();
            }
            return View(clinics);
        }

        // POST: Clinics/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,RegNo,Address,Phone,Email,SubscribedAt,BillingCycle,IsActive")] Clinics clinics)
        {
            if (id != clinics.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clinics);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClinicsExists(clinics.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(clinics);
        }

        // GET: Clinics/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clinics = await _context.Clinics
                .FirstOrDefaultAsync(m => m.Id == id);
            if (clinics == null)
            {
                return NotFound();
            }

            return View(clinics);
        }

        // POST: Clinics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var clinics = await _context.Clinics.FindAsync(id);
            _context.Clinics.Remove(clinics);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClinicsExists(int id)
        {
            return _context.Clinics.Any(e => e.Id == id);
        }
    }
}

Views/Clinics/Create.cshtml
@model Medcs.Models.Clinics

@{
    ViewData["Title"] = "Create";
}

<h2><b>Create Clinics</b></h2>

@*<h4></h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegNo" class="control-label"></label>
                <input asp-for="RegNo" class="form-control" />
                <span asp-validation-for="RegNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Clinics/Delete.cshtml
@model Medcs.Models.Clinics

@{
    ViewData["Title"] = "Delete";
}

<h2><b>Delete</b></h2>

<h3>Are you sure you want to delete this clinic?</h3>
<div>
    @*<h4>Clinics</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RegNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RegNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubscribedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubscribedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BillingCycle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BillingCycle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-primary" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Clinics/Details.cshtml
@model Medcs.Models.Clinics

@{
    ViewData["Title"] = "Details";
}

<h2><b>Details of the clinic</b></h2>
<hr />
<div>
    @*<h4>Clinics</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RegNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RegNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubscribedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubscribedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BillingCycle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BillingCycle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Clinics/Edit.cshtml
@model Medcs.Models.Clinics

@{
    ViewData["Title"] = "Edit";
}

<h2><b>Edit Clinic</b></h2>

@*<h4>Clinics</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegNo" class="control-label"></label>
                <input asp-for="RegNo" class="form-control" />
                <span asp-validation-for="RegNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubscribedAt" class="control-label"></label>
                <input asp-for="SubscribedAt" class="form-control" />
                <span asp-validation-for="SubscribedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingCycle" class="control-label"></label>
                <input asp-for="BillingCycle" class="form-control" />
                <span asp-validation-for="BillingCycle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsActive" class="control-label"></label>
                <input asp-for="IsActive" class="form-control" />
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Clinics/Index.cshtml
@model IEnumerable<Medcs.Models.Clinics>

@{
    ViewData["Title"] = "Index";
}

<h2><b>Clinics</b></h2>

<p>

    @Html.ActionLink("+Add New Clinic", "Create", "Clinics", null, new { @class = "btn btn-danger" })

</p>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table id="clinics" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubscribedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillingCycle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RegNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubscribedAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BillingCycle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsActive)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>