Models/Payments.cs
using System;
using System.Collections.Generic;

namespace Medcs.Models
{
    public partial class Payments
    {
        public int Id { get; set; }
        public int? AppointmentId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public DateTime PaidAt { get; set; }
        public byte IsReceived { get; set; }
        public string Method { get; set; }

        public Appointments Appointment { get; set; }
    }
}

Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Medcs.Models;

namespace Medcs.Controllers
{
    public class PaymentsController : Controller
    {
        private readonly medicalcenterContext _context;

        public PaymentsController(medicalcenterContext context)
        {
            _context = context;
        }


        // GET: Payments/Redirect/5
        [HttpGet]
        public ActionResult Redirect(int? id)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Redirect(int? id, [FromForm]string method)
        {
            if(method == "cash")
            {
                return LocalRedirect("/Payments/Edit/"+id.ToString());
            }
            else
            {
                return LocalRedirect("/CardPayment?id="+id.ToString());
            }
            return View();
        }

        // GET: Payments
        public async Task<IActionResult> Index()
        {
            var medicalcenterContext = _context.Payments.Include(p => p.Appointment);
            return View(await medicalcenterContext.ToListAsync());
        }

        // GET: Payments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payments = await _context.Payments
                .Include(p => p.Appointment)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (payments == null)
            {
                return NotFound();
            }

            return View(payments);
        }

        // GET: Payments/Create
        public IActionResult Create()
        {
            ViewData["AppointmentId"] = new SelectList(_context.Appointments, "Id", "Id");
            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AppointmentId,Description,Amount,PaidAt,IsReceived,Method")] Payments payments)
        {
            if (ModelState.IsValid)
            {
                _context.Add(payments);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppointmentId"] = new SelectList(_context.Appointments, "Id", "Id", payments.AppointmentId);
            return View(payments);
        }

        // GET: Payments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payments = await _context.Payments.FindAsync(id);
            if (payments == null)
            {
                return NotFound();
            }
            ViewData["AppointmentId"] = new SelectList(_context.Appointments, "Id", "Id", payments.AppointmentId);
            return View(payments);
        }

        public ActionResult Redirect()
        {
            return View();
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AppointmentId,Description,Amount,PaidAt,IsReceived,Method")] Payments payments)
        {
            if (id != payments.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(payments);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentsExists(payments.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppointmentId"] = new SelectList(_context.Appointments, "Id", "Id", payments.AppointmentId);
            return View(payments);
        }

        // GET: Payments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var payments = await _context.Payments
                .Include(p => p.Appointment)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (payments == null)
            {
                return NotFound();
            }

            return View(payments);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var payments = await _context.Payments.FindAsync(id);
            _context.Payments.Remove(payments);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentsExists(int id)
        {
            return _context.Payments.Any(e => e.Id == id);
        }
    }
}

Views/Payments/Create.cshtml
@model Medcs.Models.Payments

@{
    ViewData["Title"] = "Create";
}

@*<h2></h2>*@

<h2><b>Create Payments</b></h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AppointmentId" class="control-label"></label>
                <select asp-for="AppointmentId" class="form-control" asp-items="ViewBag.AppointmentId"></select>
                <span asp-validation-for="AppointmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsReceived" class="control-label"></label>
                <input asp-for="IsReceived" class="form-control" />
                <span asp-validation-for="IsReceived" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Method" class="control-label"></label>
                <input asp-for="Method" class="form-control" />
                <span asp-validation-for="Method" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create Payment" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Payments/Delete.cshtml
@model Medcs.Models.Payments

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Payments</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PaidAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PaidAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsReceived)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsReceived)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Method)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Method)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Appointment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Appointment.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-primary" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Payments/Details.cshtml
@model Medcs.Models.Payments

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Payments</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PaidAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PaidAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsReceived)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsReceived)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Method)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Method)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Appointment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Appointment.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Payments/Edit.cshtml
@model Medcs.Models.Payments

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Payments</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="AppointmentId" class="control-label"></label>
                <select asp-for="AppointmentId" class="form-control" asp-items="ViewBag.AppointmentId"></select>
                <span asp-validation-for="AppointmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaidAt" class="control-label"></label>
                <input asp-for="PaidAt" class="form-control" />
                <span asp-validation-for="PaidAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsReceived" class="control-label"></label>
                <input asp-for="IsReceived" class="form-control" />
                <span asp-validation-for="IsReceived" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Method" class="control-label"></label>
                <input asp-for="Method" class="form-control" />
                <span asp-validation-for="Method" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Payments/Index.cshtml
@model IEnumerable<Medcs.Models.Payments>

@{
    ViewData["Title"] = "Index";
}

<h2><b>Payments</b></h2>

<p>

    @Html.ActionLink("+Add New Payment", "Create", "Payments", null, new { @class = "btn btn-danger" })

</p>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table id="patients" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Appointment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaidAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsReceived)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Method)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                <a href="/Appointment/Details?id=@item.AppointmentId">
                    @Html.DisplayFor(modelItem => item.Appointment.Id)
                </a>
                @*@Html.DisplayFor(modelItem => item.Appointment.Id)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaidAt)
            </td>
            <td>
                @if (item.IsReceived == 1)
                {
                    <label class="success label-success">Paid</label>
                }
                else
                {
                    <label class="success label-danger">Not Paid</label>
                }
                @*@Html.DisplayFor(modelItem => item.IsReceived)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Method)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @*<a href="/CardPayment?id=@item.Id" class="btn btn-primary">Pay</a>*@

                <a href="/Payments/Redirect?id=@item.Id" class="btn btn-primary">Pay</a> |
                @*<a href="Payments/Redirect/@item.Id" class="btn btn-primary">Pay</a>*@
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

Views/Payments/Redirect.cshtml
@{
    ViewData["Title"] = "Redirect";
}

<h2>Payment Method</h2>
<form action="" method="post">
    <div class="form-group">
        <select class="form-control" name="method">
            <option value="cash">Cash</option>
            <option value="card">Card</option>
        </select>
    </div>
    <div class="form-group">
        <input type="submit" name="submit" value="Submit" class="btn btn-success"/>
    </div>
</form>