Models/Settlements.cs
using System;
using System.Collections.Generic;

namespace Medcs.Models
{
    public partial class Settlements
    {
        public int Id { get; set; }
        public int ClinicId { get; set; }
        public int DoctorId { get; set; }
        public decimal Amount { get; set; }
        public DateTimeOffset PayedAt { get; set; }

        public Clinics Clinic { get; set; }
        public Doctors Doctor { get; set; }
    }
}

Controllers/SettlementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Medcs.Models;

namespace Medcs.Controllers
{
    public class SettlementsController : Controller
    {
        private readonly medicalcenterContext _context;

        public SettlementsController(medicalcenterContext context)
        {
            _context = context;
        }

        // GET: Settlements
        public async Task<IActionResult> Index()
        {
            var medicalcenterContext = _context.Settlements.Include(s => s.Clinic).Include(s => s.Doctor);
            return View(await medicalcenterContext.ToListAsync());
        }

        // GET: Settlements/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var settlements = await _context.Settlements
                .Include(s => s.Clinic)
                .Include(s => s.Doctor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (settlements == null)
            {
                return NotFound();
            }

            return View(settlements);
        }

        // GET: Settlements/Create
        public IActionResult Create()
        {
            ViewData["ClinicId"] = new SelectList(_context.Clinics, "Id", "Address");
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "Id", "Phone");
            return View();
        }

        // POST: Settlements/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClinicId,DoctorId,Amount,PayedAt")] Settlements settlements)
        {
            if (ModelState.IsValid)
            {
                _context.Add(settlements);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClinicId"] = new SelectList(_context.Clinics, "Id", "Address", settlements.ClinicId);
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "Id", "Phone", settlements.DoctorId);
            return View(settlements);
        }

        // GET: Settlements/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var settlements = await _context.Settlements.FindAsync(id);
            if (settlements == null)
            {
                return NotFound();
            }
            ViewData["ClinicId"] = new SelectList(_context.Clinics, "Id", "Address", settlements.ClinicId);
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "Id", "Phone", settlements.DoctorId);
            return View(settlements);
        }

        // POST: Settlements/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ClinicId,DoctorId,Amount,PayedAt")] Settlements settlements)
        {
            if (id != settlements.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(settlements);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SettlementsExists(settlements.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClinicId"] = new SelectList(_context.Clinics, "Id", "Address", settlements.ClinicId);
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "Id", "Phone", settlements.DoctorId);
            return View(settlements);
        }

        // GET: Settlements/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var settlements = await _context.Settlements
                .Include(s => s.Clinic)
                .Include(s => s.Doctor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (settlements == null)
            {
                return NotFound();
            }

            return View(settlements);
        }

        // POST: Settlements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var settlements = await _context.Settlements.FindAsync(id);
            _context.Settlements.Remove(settlements);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SettlementsExists(int id)
        {
            return _context.Settlements.Any(e => e.Id == id);
        }
    }
}

Views/Settlements/Create.cshtml
@model Medcs.Models.Settlements

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Settlements</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClinicId" class="control-label"></label>
                <select asp-for="ClinicId" class ="form-control" asp-items="ViewBag.ClinicId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DoctorId" class="control-label"></label>
                <select asp-for="DoctorId" class ="form-control" asp-items="ViewBag.DoctorId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Settlements/Delete.cshtml
@model Medcs.Models.Settlements

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Settlements</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PayedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PayedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Clinic)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Clinic.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Doctor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Doctor.Phone)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-primary" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Settlements/Details.cshtml
@model Medcs.Models.Settlements

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Settlements</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PayedAt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PayedAt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Clinic)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Clinic.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Doctor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Doctor.Phone)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Settlements/Edit.cshtml
@model Medcs.Models.Settlements

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Settlements</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ClinicId" class="control-label"></label>
                <select asp-for="ClinicId" class="form-control" asp-items="ViewBag.ClinicId"></select>
                <span asp-validation-for="ClinicId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctorId" class="control-label"></label>
                <select asp-for="DoctorId" class="form-control" asp-items="ViewBag.DoctorId"></select>
                <span asp-validation-for="DoctorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PayedAt" class="control-label"></label>
                <input asp-for="PayedAt" class="form-control" />
                <span asp-validation-for="PayedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Settlements/Index.cshtml
@model IEnumerable<Medcs.Models.Settlements>

@{
    ViewData["Title"] = "Index";
}

<h2><b>Settlements</b></h2>

<p>
    @Html.ActionLink("+Add New Settlements", "Create", "Settlements", null, new { @class = "btn btn-danger" })

</p>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@

<table id="settlements" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PayedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Clinic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Doctor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PayedAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Clinic.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Doctor.Phone)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>